version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=evoting
      - DB_PASSWORD=your_password
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret
      - PORT=3001
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - evoting-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=evoting
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./evoting_database_schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - evoting-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - evoting-network

volumes:
  db-data:

networks:
  evoting-network:
    driver: bridge
